parsedatetime/__init__.py, parsedatetime/pdt_locales.py, parsedatetime/tests/TestNlp.py, parsedatetime/tests/TestSimpleDateTimes.py, parsedatetime/tests/TestSimpleOffsets.py
Here I have met a weird bug that a datetime str (flag 3) has been detected as time str (flag 2). Like this:
```python
import parsedatetime as pdt
pdt.Calendar().parse('friday afternoon 3pm')
```
After I enabling the debug level logging:
```
...
2015-05-06 19:32:19,857 DEBUG: parse (bottom) [  after  3pm][noon][  after][ 3pm]
...
```
So the reason is because https://github.com/bear/parsedatetime/blob/master/parsedatetime/__init__.py#L1631-L1643 split word "afternoon" into "after" and "noon". And the remain "after" causes `Calendar._evalModifier2` being called and dropped the existed `dateFlag = 1` (So perhaps there's another bug in `_evalModifier2`).
In this fix I added "afternoon" phrase in "re_sources", and use `\b` to prevent words being split.
I have all tests passed on my machine.
=> Bunch of bugfixes (see comments)

parsedatetime/__init__.py, parsedatetime/tests/TestSimpleDateTimes.py
The meridian keywords a, p, am, and pm are being picked out when found as prefixes of longer words. For example, "10 pounds" is parsed the same as "10 PM ounds" or "10 p ounds." The pull request adds a word boundary to the meridian regular expression and a fairly exhaustive test of word boundaries against all keywords in the locale (e.g. "1 amfoo" "1 todayfoo"). I'm not sure whether all of the keywords would parse to a date without the "foo" suffix, but it makes for a simple test.
The majority of failing cases were fixed by @philiptzou in #85 introducing word boundaries to a different regex (e.g. "10 dogs" parsed like "10 d ogs"). As far as I could tell, only the meridian was still affected.
This bug was originally reported [over …
=> Meridian keywords not requiring word boundaries ("10 pounds" == "10 PM ounds")

parsedatetime/__init__.py, parsedatetime/tests/TestNlp.py
Fixes #87 for which I had previously employed a workaround in my application to pre-process transform *next month* to *in 1 month*. I am submitting this as a pull request in the hope of some feedback or additional test cases. `nlp()` is somewhat under-tested; while I was able to find and fix a few resulting issues there are probably more cases to test. I would like to have a few eyes on this before I merge it in.
It would not be acceptable to pull out standalone units as dates; simply mentioning the word "week" does not imply a specific date. Instead I required that these units be immediately preceded by a modifier, such that *next week* parses as a date but neither *A week is a long time* nor *Next I will rest for a week* parse as dates.
One detail of the orginal nlp implementation stuck …
=> Fixes "next week" and similar modifier + unit pairs in nlp()

parsedatetime/__init__.py, parsedatetime/pdt_locales.py, parsedatetime/tests/TestConvertUnitAsWords.py, parsedatetime/tests/TestSimpleOffsets.py, parsedatetime/tests/TestSimpleOffsetsHours.py
*1 month* == *one month* == *a month*
*1 hour* == *one hour* == *an hour*
This change uncovered some bugs that otherwise might have gone unnoticed. Much like the single-letter variants of "month" and "year," adding the single letter "a" to represent a number caused a bunch of tests to fail because "a" is a common letter in other words. The worst offenses that I noticed were "11 AM" parsing as if it were written "11PM 1m" and "1 day" parsing as "1d 1y." Other number words like "one" and "nine" as part of larger words could have caused problems but it was probably not very common for conditions to be just right for the parser to pick that up.
All those failing tests were the motivation for 3dc5d0bd35a21d5d4e2a8170b9ef17cc3cb38ddb.
Just a few minor word boundary regex tweaks to get things …
=> Add "a" and "an" for phrases like "a week from now"

parsedatetime/__init__.py, parsedatetime/tests/TestNlp.py, parsedatetime/tests/TestSimpleDateTimes.py
For example, neither "$300" nor "300ml" are intended to be "3:00" but "300" and "300am" are fine. The time must be preceded by a space or hyphen (the hyphen is to allow *300-400* style ranges) or appear at the beginning of the string. The time (or time + meridian for AM/PM locales) must be followed by a word boundary.
I opted for `(\s|-|^)` here since, especially considering currencies, many different symbols can precede a number and most will be treated as a word boundary. `\b` would not have fixed the *$300* case. 
This is another one where I'm not sure if all cases are covered but the tests pass and it seems in general to be an improvement. 
I did not make any changes to `evalRanges` via `RE_RTIMEHMS` and `RE_RTIMEHMS2` which look like they may still have word boundary issues. Both …
=> Avoid parsing numbers within larger strings as if they were times

parsedatetime/__init__.py, parsedatetime/tests/TestErrors.py
`parsedatetime` failed when parsing strings like "548548 W". Actually it should not be treated as a date...
The reason it failed is because python's `datetime` module only accept year larger than 0 or smaller than 9999.
This fix just ignores the OverflowError when it happened and then returns the original datetime.
Tests has been added.
=> Prevented datetime module raising OverflowError when year reached 10000

parsedatetime/__init__.py, parsedatetime/tests/TestSimpleDateTimes.py
The yyyy/mm/dd format is the primary or secondary date format in about two dozen countries. Additionally, the international standard yyyy-mm-dd ISO 8601 date format is widely used and worth supporting as it transcends locales and is used often in the government and technical fields.
This pull request adds year-first date support by testing whether the first number is greater than 31 and if so assuming yyyy/mm/dd instead of the locale's date formatting order. The date regex has been modified to allow year-first as an entirely alternate case to xx/xx/yyyy (so that it is not possible to match something like 1234/56/7890 as a date). It is worth noting that according to Wikipedia only one country, Kazakhstan, uses yyyy.dd.mm format, but ICU does not reflect that format.
I did not go into the …
=> Adds yyyy/mm/dd and ISO 8601 yyyy-mm-dd support

parsedatetime/__init__.py, parsedatetime/context.py, parsedatetime/pdt_locales.py, parsedatetime/tests/TestContext.py, parsedatetime/tests/TestPhrases.py, parsedatetime/tests/TestStartTimeFromSourceTime.py, parsedatetime/warns.py
This is a refactor of current `parsedatetime` module. I removed all `*Flag` attributes from `Calendar` object and used thread-safe `pdtContext` to replace them. There are two huge methods in `Calendar` class, the `parse()` and `_evalString()`. They have been broke up into several small methods.
Also, this pull request introduced a new system to record if certain datetime string contains year, month, week, day, hour, minute, second, halfday (for example, afternoon or midnight) or "now". With such ability, not only we can know if the string contains date/time, but also the accuracy of date/time it brings with.
Method `parse()` and `parseDT()` are both added a new parameter "version". When `version` equals to 1 which is also the current default value, the methods' second return value is …
=> Thread-safe context & accuracy flag

README.rst
Fixes: https://github.com/bear/parsedatetime/issues/112
@bear Does this example work in all cases you can imagine?  I tried with `"tomorrow"`, `"4:30 pm"`, and `"2015-08-08"`.  I realized that the second item in the tuple that's returned from `Calendar.parse` changes the type of object that's returned as the first item, but both cases I saw worked fine when passed to `mktime`.
=> Add datetime example to readme.

parsedatetime/__init__.py, parsedatetime/pdt_locales.py, parsedatetime/tests/TestDelta.py
=> Allowed real number appear in text like "5.5 days ago"

parsedatetime/__init__.py, tests/TestComplexDateTimes.py
Which cause certain strings with format like "MM DD, YYxx xx:SS" parsed incorrectly.
See #137
=> bug(date3): rely on comparison of hour and year strings but not strict char position

.travis.yml, parsedatetime/__init__.py, parsedatetime/pdt_locales/base.py, parsedatetime/pdt_locales/icu.py, setup.py, tests/TestComplexDateTimes.py, tests/TestLocaleBase.py, tests/TestSimpleDateTimes.py, tests/utils.py
As the title described. After installing PyICU a lot of test cases are failed. This patch fixed all the test cases and added 3 environments to Travis CI for testing circumstances of different Python versions when PyICU is installed.
But we'll skip PyPy with PyICU since PyICU causes segment fault.
=> Fixed all PyICU test failure

tests/TestStartTimeFromSourceTime.py
This test fails in december, because the source time of calculation (s)
is in the next year (because it is generated after yr += 1).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/146)
=> Test failure: eom is correct, but expectation is wrong

parsedatetime/pdt_locales/icu.py
as this is the only place where this type of code was found, I just unwrapped it so python 2.6 was still viable
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/157)
=> unwrap dictionary comprehensions to allow for python 2.6 to work - Issue #156

parsedatetime/__init__.py, tests/TestSimpleOffsetsNoon.py
Fixes cases of relative times with CRE_TIME patterns like "noon", "lunch", etc, for example: `5 minutes before noon tomorrow`, `1 hour after dinner`.  These evaluations were getting offset by an entire day forward/backwards based on the word before or after.
```
>>> pdt.Calendar().nlp("One hour after dinner") # today is 5/3
((datetime.datetime(2016, 5, 4, 20, 0), 2, 0, 21, 'One hour after dinner'),)
>>> pdt.Calendar().nlp("One hour after dinner")
((datetime.datetime(2016, 5, 3, 20, 0), 2, 0, 21, 'One hour after dinner'),)
```
This might be dangerous territory, but I cannot figure out the intention of the code which was causing this issue - I see that it has been copy/pasted/ported through a number of refactors and suspect that it has been made obsolete and is now only causing problems. …
=> fix (by deletion?) "some duration before noon/dinner/etc"

README.rst
construct datetime object directly `datetime(*tt[:6])` instead of using `fromtimestamp(mktime(tt))` (timezone issues are more likely than leap seconds issues).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/163)
=> update code example in readme

parsedatetime/__init__.py, tests/TestComplexDateTimes.py, tests/TestNlp.py
Well, honestly this issue is immediately top of the list for "Most Amusing Bug of 2016".  We were puzzled as to why our app was behaving incorrectly whenever the word "ass" was used in a sentence.  We soon found that parsedatetime is treating "ass" as a time:
```
>>> import parsedatetime
>>> parsedatetime.Calendar().nlp("nice ass")
((datetime.datetime(2016, 8, 10, 20, 5, 35), 2, 5, 8, 'ass'),)
```
We tracked the issue down to a curious QUNITS regular expression which matches the word "a" as the number 1, the letter "s", and then another "s" for "seconds" (it would also match the word "ash" via the same logic with "hours").  We couldn't quite make sense of the second "s" in the regular expression and believe it should have been "\s" instead - making that change fixes the issue.
This PR …
=> fix "ass" being interpreted as a time

parsedatetime/pdt_locales/en_AU.py
I had an Australian user noticing errors due to missing "short" time format. As it turned out, every format except "long" was missing. The previous implementation accidentally removed all other formats.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/180)
=> Fixed override of the long time format for Australian locale

parsedatetime/__init__.py, tests/TestComplexDateTimes.py
This fixes a scenario previously reported as #165, in which the date is parsed incorrectly when a day is provided (e.g. "tuesday august 23nd 2016 at 5pm").  This particular fix works by ignoring the day if the date is already parsed out - it might be more informative to actually compare the reference date to the parsed out day and log or produce an error if they're not consistent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/178)
=> fix date interpretation when day is also provided (#165)

parsedatetime/pdt_locales/base.py, tests/TestSimpleDateTimes.py
The meridian regex in the base locale used unescaped periods to match *a.m.* and *p.m.* which caused any four-character phrase matching that pattern to be interpreted as a meridian. I added tests to make sure that *3 axpx* and *3 pxmx* are not interpreted as times.
Note that most non-word characters like *3 p-x.* or *3 p m* will still match because the meridian regex also matches the single characters `p` and `a` followed by any word boundary. With `nlp` you can easily see that both of those cases match only the *3 p* portion.
I bumped into this problem while working on the nlp whitespace handling. It is a nice bite-sized fix, should be fine for inclusion in 2.2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Fixes false meridians (four-letter a*m* or p*m* words like "3 puma")

parsedatetime/__init__.py, tests/TestSimpleDateTimes.py
A missing “+” for a whitespace match between month name and year is causing the year to not parse when an extra space is provided.  E.g:
```
>>> parsedatetime.Calendar().parse("August 2016")
(time.struct_time(tm_year=2016, tm_mon=8, tm_mday=1, tm_hour=16, tm_min=41, tm_sec=35, tm_wday=1, tm_yday=236, tm_isdst=1), 1)
>>> parsedatetime.Calendar().parse("August  2016")
(time.struct_time(tm_year=2017, tm_mon=8, tm_mday=1, tm_hour=20, tm_min=16, tm_sec=0, tm_wday=1, tm_yday=236, tm_isdst=1), 3)
```
This PR adds the missing “+” and a test for the scenario.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/181)
=> fix for extra space before year causing bad parse

parsedatetime/__init__.py, parsedatetime/pdt_locales/base.py, tests/TestNlp.py
As discussed in #181 it should be possible to remove the pre-processing in `nlp` and `parse` to remove periods followed by spaces and quotes followed or preceded by spaces since the regular expressions now use word boundaries. There are several things that I want to discuss in this pull request.
I am not yet fully convinced that removing the pre-processing is necessary. It caused minor problems with meridian and month abbreviations and took a bit more regex cleanup to fix than I anticipated. There is a discussion below on testing, I think that more comprehensive testing will be necessary before merging this to v3.
The basic problems involved the phrase not quite matching what you would expect:
``` python
>>> cal.nlp('5 A.M.')
((datetime.datetime(2016, 9, 10, 5, 0), 2, 0, 3, '5 A'),)
>>> …
```
=> Avoid discarding periods and quotes in nlp and parse

parsedatetime/__init__.py, tests/TestDayStartHour.py, tests/TestLocaleBase.py, tests/TestNlp.py, tests/TestPhrases.py, tests/TestSimpleOffsets.py
When creating a Calendar, allow the day start hour to be passed in.
By default, remains at 9 - the way it currently is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/203)
=> Allow day start hour to be configurable - by default 9 as now

parsedatetime/__init__.py, parsedatetime/pdt_locales/icu.py, tests/TestComplexDateTimes.py, tests/TestConvertUnitAsWords.py, tests/TestPhrases.py, tests/TestRussianLocale.py, tests/TestSimpleDateTimes.py, tests/TestSimpleOffsets.py, tests/TestSimpleOffsetsNoon.py
CI tests will currently fail due to some changes in pycodestyle 2.2.0. The issues were not serious so although some of the code (unit tests) will soon be obsolete I just fixed the code to avoid problems for other contributors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/204)
=> Fixed code formatting for pycodestyle 2.2.0

setup.py
- The `pytest_runner` dep exists in testing-requirements that is sourced
by `tox.ini`, so it should work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/220)
=> fix(setup, #219): drop `setup_requires` from setup.py

parsedatetime/pdt_locales/base.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/233)
=> Add 'secs' and 'mins' into base units

parsedatetime/__init__.py
Adds a constant specifying the start hour for all relative calculations when self.StartTimeFromSourceTime is False.
parsedatetime uses 09:00 as the start of the day for relative calculations, but that time is not currently configurable.   09:00 is the traditional start of the workday in the the US and other countries, but in many countries 07:00 or 08:00 is traditional. 
There's also a use case for being able to set the start of the day to 00:00:00.
I considered adding configuration to set hour/minute/second, but thought just hour would satisfy most use cases and require less code change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/225)
=> Add a constant for start hour

parsedatetime/pdt_locales/icu.py, parsedatetime/pdt_locales/nl_NL.py
Fixes parsedatetime lint errors for flake8 v3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0).   Required to be fixed before tests will run.  The nl_NL.py error references "different values" for 'vorige' key, but to my eye they are the same.
```
$ make test
flake8 parsedatetime > violations.flake8.txt
Makefile:54: recipe for target 'lint' failed
make: *** [lint] Error 1
$ cat violations.flake8.txt
parsedatetime/pdt_locales/icu.py:141:5: E741 ambiguous variable name 'l'
parsedatetime/pdt_locales/nl_NL.py:74:5: F601 dictionary key 'vorige' repeated with different values
parsedatetime/pdt_locales/nl_NL.py:80:5: F601 dictionary key 'vorige' repeated with different values
$ flake8 --version
3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.5.2 on Linux
$ git …
```
=> Fix lint errors for flake8 v3.5.0

parsedatetime/pdt_locales/icu.py
This is my proposed patch for #221.
Sanitation of day / month names is required as ICU includes periods in many abbreviations that render them unmatchable. This patch mostly contain a sanitation function intended to remove "." (periods) at the end of a string, or before a "|" separator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/222)
=> Fix to sanitize abbreviated months from icu

parsedatetime/__init__.py
The logging identifies which expressions produce a leftmost match as `nlp` moves its way through the input string. It will not log every match, only the ones that are better than the previous match. This was necessary to resolve a few cases of `nlp` sending what seemed to be the wrong text to `parse` once I started tinkering with the period and quotes pre-processing step in `nlp`.
See #193
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/194)
=> Added simple logging in nlp

README.rst
* The first title is now a title
* The python code blocks are now syntax highlighted
* OSX -> macOS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/244)
=> Polished README.rst

parsedatetime/pdt_locales/icu.py
Newer versions of pyicu should be imported as
import icu 
whereas
import PyICU 
will print a warning.
This fix uses the preferred import if available and otherwise falls back to the older name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/242)
=> fix pyicu import to suppress warnings

parsedatetime/pdt_locales/icu.py
``
File "/usr/local/lib/python2.7/dist-packages/parsedatetime/pdt_locales/icu.py", line 56, in get_icu
result['icu'] = icu = pyicu.Locale(locale)
AttributeError: 'module' object has no attribute 'Locale'
``
Hi all.
The https://github.com/openaps/openaps project (very indirectly) uses `parsedatetime` and in the last few weeks a problem has emerged with `AttributeError: 'module' object has no attribute 'Locale'`. This PR _seems_ to fix it - at least in how we're using it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/248)
=>  pyicu 'module' object has no attribute 'Locale'

parsedatetime/__init__.py
-- currently result for `last 10 days` is not correct. 
-- Why 
- lib checks for `unit` `chunk1` `chunk2`
-  `unit` should be one of "days"/"months"/"weeks" etc. Which work well for `next week`, `last week` queries.
-  for queries like `next 2 days`, `last 10 days` --> it doesn't recognise `unit` correctly and falls back to `else` case which just adds 10 future days / month in current time
- add `elif` cases with  `unit.isdigit()` condition which will take care of such cases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/255)
=> support 'next 10 days' query

parsedatetime/__init__.py, tests/__init__.py
Strip out all explicit logging setup calls
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/270)
=> Logging in Python 3 is a bit different, especially within a module

parsedatetime/__init__.py
When parsing "this afternoon" we are not passing to the recursive parse() calls any sourceTime values given
Add sourceTime to the call for when CRE_TIME match happens when parsing the remaining text chunks
Fixes #274
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/276)
=> [Issue 274] include sourceTime to recursive parse() calls

README.md, parsedatetime/__init__.py, tests/TestInc.py
Recently ran a typo checker through a project in which we use parsedatetime.  Went ahead and ran it through the parsedatetime repo and found a couple more.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bear/parsedatetime/287)
=> Fix a number of typos / spelling errors found when running project through a typo checker.
